default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-watch-list_development
  # database: rails_watch_list_development

test:
  <<: *default
  database: rails-watch-list_test
  # database: rails_watch_list_test
